setwd("C:/Users/lgautam/Desktop/HeaMap_RBL_gene")
library(pheatmap)
library(grid)
library(ggplot2)
library(matrixStats)
library(tidyverse)
data <-read.csv('cilia_gene_Heatmap.csv')
dim(data)
head(data)
data1 <- as.matrix(data[,-1])
rownames(data1) <- data[,1]
pheatmap(data1)
pheatmap(log2(data1 +1), scale = 'row')
pheatmap(log2(data1 +1), scale = 'row', row.names = FALSE)
my_plot <- pheatmap(log2(data1 +1), scale = 'row', row.names = TRUE, show_rownames = F, treeheight_row = 20)
plot_dims <- get_plot_dims(my_plot)
png("AIO_plot.png", res = 72)
